---
language: python
branches:
  only:
    - master
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit

python:
  - "3.7"
  - "3.8"

install:
  - pip install tox-travis

script:
  - tox

after_success:
  coveralls
