---
language: python
dist: xenial
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit

python:
  - "3.7"

install:
  - pip install -U -r requirements.txt

script:
  - make lint
  - make coverage

after_success:
  coveralls
